

name: cicd

on:
  push: 
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read
  id-token: 'write'

jobs:
  init:
    runs-on: ubuntu-latest

    env:
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}

    steps:
      # Checkout repository to GitHub action runner
      - name: Checkout
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: 'projects/908852839842/locations/global/workloadIdentityPools/quest/providers/quest-github'
          service_account: 'inf-sa@seed-440521.iam.gserviceaccount.com'

      # Replacing placeholders in Terraform files
      - name: Replacing placeholders
        run: |
          echo "***** Replacing placeholders with GIT_TOKEN *****"
          sed -i "s|\[PASSWORD\]|${{ env.GIT_TOKEN }}|g" *.tf
        working-directory: Org-Templates

      # Terraform Init
      - name: Terraform Init
        run: |
          cd Org_Template/terraform-google-cloud-folder
          terraform init --reconfigure

  validate:
    runs-on: ubuntu-latest
    needs: init
    env:
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}

    steps:
      # Checkout repository to GitHub action runner
      - name: Checkout
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: 'projects/908852839842/locations/global/workloadIdentityPools/quest/providers/quest-github'
          service_account: 'inf-sa@seed-440521.iam.gserviceaccount.com'

      # Replacing placeholders in Terraform files
      - name: Replacing placeholders
        run: |
          echo "***** Replacing placeholders with GIT_TOKEN *****"
          sed -i "s|\[PASSWORD\]|${{ env.GIT_TOKEN }}|g" *.tf
        working-directory: Org-Templates

  tflint:
    needs: validate
    uses: ./.github/workflows/lint.yaml

  plan:
    runs-on: ubuntu-latest
    needs: tflint
    env:
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}

    steps:
      # Checkout repository to GitHub action runner
      - name: Checkout
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: 'projects/908852839842/locations/global/workloadIdentityPools/quest/providers/quest-github'
          service_account: 'inf-sa@seed-440521.iam.gserviceaccount.com'

      # Replacing placeholders in Terraform files
      - name: Replacing placeholders
        run: |
          echo "***** Replacing placeholders with GIT_TOKEN *****"
          sed -i "s|\[PASSWORD\]|${{ env.GIT_TOKEN }}|g" *.tf
        working-directory: Org-Templates

      # Terraform Plan
      - name: Terraform Plan
        run: |
          cd Org_Template/terraform-google-cloud-folder
          terraform init -reconfigure
          terraform plan --var-file=folder.tfvars --var-file=orgpolicy.tfvars

  apply-destroy:
    runs-on: ubuntu-latest
    needs: plan
    environment: Production
    if: github.ref == 'refs/heads/main'
    env:
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}

    steps:
      # Checkout repository to GitHub action runner
      - name: Checkout
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: 'projects/908852839842/locations/global/workloadIdentityPools/quest/providers/quest-github'
          service_account: 'inf-sa@seed-440521.iam.gserviceaccount.com'

      # Replacing placeholders in Terraform files
      - name: Replacing placeholders
        run: |
          echo "***** Replacing placeholders with GIT_TOKEN *****"
          sed -i "s|\[PASSWORD\]|${{ env.GIT_TOKEN }}|g" *.tf
        working-directory: Org-Templates

      # Terraform Apply
      - name: Terraform Apply
        run: |
          cd Org-Templates
          terraform init -reconfigure
          terraform apply --var-file=folder.tfvars --var-file=orgpolicy.tfvars --auto-approve -input=false
          # terraform destroy --var-file=folder.tfvars --auto-approve

    
