

name: cicd

on:
  push: 
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read
  id-token: 'write'


jobs:
  init:
    runs-on: ubuntu-latest
    defaults:
      run: 
        shell: bash      
    env: 
      WORKING-DIRECTORY: Org-Templates
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    
  

    steps:
      # Checkout repository to GitHub action runner
      - name: Checkout
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: '${{ secrets.WIF }}'
          service_account: '${{ secrets.SA }}'

      # Replacing placeholders in Terraform files
      - name: Replacing placeholders
        run: |
          echo "***** Replacing placeholders with GIT_TOKEN *****"
          sed -i "s|\[PASSWORD\]|${{ env.GH_TOKEN }}|g" *.tf
        working-directory: ${{ env.WORKING-DIRECTORY }}

      # Terraform Init
      - name: Terraform Init
        working-directory: ${{ env.WORKING-DIRECTORY }}
        run: |
          terraform init 
          terraform init -upgrade 
        
        

  validate:
    runs-on: ubuntu-latest
    needs: init
    env: 
      WORKING-DIRECTORY: Org-Templates
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      # Checkout repository to GitHub action runner
      - name: Checkout
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: '${{ secrets.WIF }}'
          service_account: '${{ secrets.SA }}'

      # Replacing placeholders in Terraform files
      - name: Replacing placeholders
        run: |
          echo "***** Replacing placeholders with GIT_TOKEN *****"
          sed -i "s|\[PASSWORD\]|${{ env.GIT_TOKEN }}|g" *.tf
        working-directory: ${{ env.WORKING-DIRECTORY }}
 

  tflint:
    needs: validate
    uses: ./.github/workflows/lint.yml

  plan:
    runs-on: ubuntu-latest
    needs: tflint
    env: 
      WORKING-DIRECTORY: Org-Templates
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      # Checkout repository to GitHub action runner
      - name: Checkout
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: '${{ secrets.WIF }}'
          service_account: '${{ secrets.SA }}'

      # Replacing placeholders in Terraform files
      - name: Replacing placeholders
        run: |
          echo "***** Replacing placeholders with GIT_TOKEN *****"
          sed -i "s|\[PASSWORD\]|${{ env.GH_TOKEN }}|g" *.tf
        working-directory: ${{ env.WORKING-DIRECTORY }}

      # Terraform Plan
      - name: Terraform Plan
        working-directory: ${{ env.WORKING-DIRECTORY }}
        run: |
          terraform init -upgrade
          terraform plan --var-file=folder.tfvars --var-file=orgpolicy.tfvars

  apply:
    runs-on: ubuntu-latest
    needs: plan
    environment: Production
    if: github.ref == 'refs/heads/main'
    env: 
      WORKING-DIRECTORY: Org-Templates
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      # Checkout repository to GitHub action runner
      - name: Checkout
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: '${{ secrets.WIF }}'
          service_account: '${{ secrets.SA }}'

      # Replacing placeholders in Terraform files
      - name: Replacing placeholders
        run: |
          echo "***** Replacing placeholders with GIT_TOKEN *****"
          sed -i "s|\[PASSWORD\]|${{ env.GH_TOKEN }}|g" *.tf
        working-directory: ${{ env.WORKING-DIRECTORY }}

      # Terraform Apply
      - name: Terraform Apply
        working-directory: ${{ env.WORKING-DIRECTORY }}
        run: |
          terraform init -upgrade
          terraform apply --var-file=folder.tfvars --var-file=orgpolicy.tfvars --auto-approve -input=false
          # terraform destroy --var-file=folder.tfvars --auto-approve

    
